import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase'
import { logAudit } from '@/lib/auth'

// GET /api/kazu — list all kazu for current user
export async function GET(req: NextRequest) {
  const supabase = createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const status = searchParams.get('status')
  const search = searchParams.get('search')

  let query = supabase
    .from('kazu')
    .select(`
      *,
      kliente:profiles!kazu_kliente_id_fkey(id, full_name, email, phone),
      advogadu:profiles!kazu_advogadu_id_fkey(id, full_name, email),
      timeline:kazu_timeline(*)
    `)
    .order('created_at', { ascending: false })

  if (status && status !== 'hotu') query = query.eq('status', status)
  if (search) query = query.or(`titulo.ilike.%${search}%,kazu_number.ilike.%${search}%`)

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ data })
}

// POST /api/kazu — create new kazu (advogadu only)
export async function POST(req: NextRequest) {
  const supabase = createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json()
  const { titulo, tipo, description, kliente_id, urgency, start_date, expected_end } = body

  const { data, error } = await supabase
    .from('kazu')
    .insert({
      titulo,
      tipo,
      description,
      kliente_id,
      advogadu_id: user.id,
      urgency: urgency || 'normal',
      start_date: start_date || new Date().toISOString().split('T')[0],
      expected_end,
      kazu_number: '', // auto-generated by trigger
    })
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Default timeline steps
  const defaultSteps = [
    { kazu_id: data.id, step_name: 'Konsultasaun', step_order: 1, status: 'active' },
    { kazu_id: data.id, step_name: 'Prepara Kazu',  step_order: 2, status: 'pending' },
    { kazu_id: data.id, step_name: 'Dosie Kompletu',step_order: 3, status: 'pending' },
    { kazu_id: data.id, step_name: 'Audiensia',     step_order: 4, status: 'pending' },
    { kazu_id: data.id, step_name: 'Desizaun',      step_order: 5, status: 'pending' },
  ]
  await supabase.from('kazu_timeline').insert(defaultSteps)

  await logAudit(user.id, 'kazu_create', `Kazu foun kriada: ${data.kazu_number}`, 'kazu', data.id)
  return NextResponse.json({ data }, { status: 201 })
}
